server:
  port: 8082
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db_commodity?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      min-idle: 20
      max-active: 60
      initial-size: 20
      max-wait: 30000
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
