server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000